application: # set your application-id.
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

builtins:
- admin_redirect: on
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: statics/images/favicon.ico
  upload: statics/images/favicon.ico
  mime_type: image/x-icon
  secure: never

- url: /_generated_media
  static_dir: _generated_media
  secure: never

- url: /_media
  static_dir: kay/media
  secure: never

- url: /js
  static_dir: statics/javascripts
  secure: never

- url: /css
  static_dir: statics/stylesheets
  secure: never

- url: /ja/
  static_files: statics/html/index_ja.html
  upload: statics/html/index_ja.html

- url: /en/
  static_files: statics/html/index_en.html
  upload: statics/html/index_en.html

- url: /_kay/.*
  script: kay/main.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: always
  login: admin

- url: /_ah/queue/deferred
  script: kay/main.py
  login: admin

- url: /_ah/test.*
  script: kay/ext/testutils/gaeunit.py
  login: admin

- url: /.*
  script: kay/main.py
  secure: never

- url: /_api/.*
  script: api.py
  secure: always
  # login: required

skip_files: |
  ^(.*/)?(
  (#.*#)|
  (.*\.po[t]*)|
  (.*\.py[co])|
  (.*~)|
  (LICENSE)|
  (README)|
  (README\.pdf)|
  (TODO)|
  (TODO\.pdf)|
  (\..*)|
  (_backup/.*)|
  (app\.ya*ml)|
  (app\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (dev_appserver.datastore)|
  (gaema-LICENSE)|
  (index\.ya*ml)|
  (index\.yaml\.sample)|
  (kay\/docs\/.*)|
  (kay\/lib\/babel\/localedata\/.*)|
  (kay\/management\/.*)|
  (manage\.py)|
  )$
